version: '3'
services:
  telegraf:
    image: telegraf:1.5    
    hostname: ${HOSTNAME}
    container_name: tick_telegraf
    volumes:
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      OUTPUTS_INFLUXDB_URLS: udp://10.240.152.164:8089
      AGENT_HOSTNAME: ${HOSTNAME}
    # ports:
      # - "8092:8092/udp"
      # - "8094:8094"
      # - "8125:8125/udp"    