version: '3'
# docker stack deploy -c docker-monit.yml monitor
services:
  # Define a Influxdb service
  influx:
    image: influxdb:1.3
    container_name: influx
    ports:
      - 0.0.0.0:8087:8086
      - 0.0.0.0:8089:8089/udp
    env_file:
      - $PWD/influxdb.env
    volumes:
      - ./data/influxdb:/var/lib/influxdb
      - $PWD/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    # networks:
    #   - monitoring_network
  # Define a Telegraf service
  telegraf:
    image: telegraf:1.5    
    hostname: ${hostname}
    volumes:
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      OUTPUTS_INFLUXDB_URLS: udp://influx:8089
      AGENT_HOSTNAME: ${hostname}
    # networks:
    #   - monitoring_network
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
    links:
      - influx
  # Define a Chronograf service
  chronograf:
    image: chronograf:1.4
    environment:
      INFLUXDB_URL: http://influx:8086
      KAPACITOR_URL: http://kapacitor:9092
      INFLUXDB_USERNAME: developer
      INFLUXDB_PASSWORD: vtcc@123
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    ports:
      - "8889:8888"
    links:
      - influx
      - kapacitor
    # networks:
    #   - monitoring_network

  # Define a Kapacitor service
  kapacitor:
    image: kapacitor:1.3.3
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influx:8086
      INFLUXDB_USERNAME: developer
      INFLUXDB_PASSWORD: vtcc@123
    ports:
      - "9092:9092" 
    links:
      - influx
    # networks:
    #   - monitoring_network

# volumes:
#   influx:
#     driver: local
#   grafana:
#     driver: local

# networks:
#   monitoring_network: